name: "Dev Deployment"

on:
  push:
    branches:
      - feat/agent-ai-module

env:
  NAME: blox3-v1-prod
  ZONE: asia-southeast1-a

jobs:
  build-deploy:
    name: Build and deploy application to server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.MY_REPO_PAT_NEW }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.DEPLOY_SERVER }}
          port: ${{ vars.SSH_PORT }}
          username: ${{vars.SSH_USER}}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/massbit/phidata_ai/live-assistant
            git checkout feat/agent-ai-module
            git pull
            source aienv/bin/activate
            phi ws down -y
            phi ws up -y
